os: linux
language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- pip install coveralls flake8
script:
- python3 setup.py install
- flake8 --ignore=E722 --max-line-length=120 --exclude=venv,__pycache__ .
before_deploy:
- python3 setup.py bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: JYuz4ElYWPfYZfa4Nu+LJ660FnehOxVLnkEPQL19RlpJtWu0zPXOjSqrplaDfG88o3SZ4xAonTjUgSfuZT+0DvP/EC5cI78Q+nFco1FP2v2hlRxtym08MXlxmZqxCxuQdkyn0ylGOqIJkvkSUiw98uPc1QCLSBWbI9i6kw6uSsKhTbq6Cy00P9iHtLtWfGj47W4zpUK14RVuPLQ5smckmtLD5Rgf5gu08+R9+vVImz9UeTp2JGt3pRUiJt6FTMlviUdd+0HdnphYuEWPJm1QyxZxe2ZZS70wYgkkiUyMZ9wIeRQPTQl+fa+wwhpRdUq1G3RtOGEHDkCMyczVy3N/ZN+vG6xzMiGWK0jRT9RB+f1xEZmYcrFScH7iGBiqFOaOozQ9J5CwuQgyI0lR7F01nMxk85tLYj3zJ+UbMRj8DSE6V+zg2KszcnxMYBaMS8vf4XI15vWhBFMQqoV55r7UHFnyf6ChCUuy/JP4Krtks47syU/qKyT80FY/uzr2nJsbCLKhggXFbV32DEmLSnawxT067mO7MO8SjWBCU/NIfor5bIadjOXBPO4IZnZUgppI7GPi/2uWbO+DHBJ3FMqEolxui2+StclVPY9cT/3ZWPGgBjc0TyGO68XM8aFqfmYz2SPeV00Zfwptx6Zn7lRNbYOBUBpUwlih3wkRl3Lo0j0=
  file: dist/spider-1.0-py3-none-any.whl
  overwrite: true
  on:
    tags: true
    all_branched: true
    repo: VirtualJudge/spider
